### ISSUE TITLE
Build and Optimize Landing Page for Mobile View

### ISSUE THREAD

**Issue by Calebux** [mubarak23/chainevents-frontend#1]
Optimize our simple landing page for mobile responsiveness. 

The main tasks include:

**Mobile View Optimization:** Ensure the layout looks great and functions smoothly across different mobile screen sizes.
**Gradient Style:** Follow the existing gradient styles used on the page for consistency.
**Color Scheme:** Adhere to the current color scheme to maintain brand uniformity.

Figma Link: https://www.figma.com/design/Z1IebD0dM4HMDDnlxzhV6R/Untitled?node-id=801-1512&node-type=canvas&t=tRf2C0gaILTQeHdU-0

**Comment by joeperpetua** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
3+ years experience doing Full Stack Development with JS/TS

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello i am a frontend developer and cairo developer and i believe i would be able to tackle this issue effectively. I have experience with building web applications and dapps. And i would be gald to take this up.

### How I plan on tackling this issue
I would develop the page perfectly according to the figma design and also make sure that it is responsive in all screens. I will make sure to adopt best practices when builidng to ensure a pixel perfect build

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue, I'll take the following steps:

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Please kindly assign :)

### How I plan on tackling this issue
i would make it responsive and pixel perfect 
please kindly assign

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by Samuel1-ona** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

My background and how it can be leveraged
Hello  a blockchain developer. I will love to work on this issue

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
ETA - 3 days

**Comment by stephanniegb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I’m a frontend engineer with  experience in building responsive, interactive UIs. I’ve worked on implementing pixel-perfect designs, and optimizing performance across various projects. My frontend technologies like css and tailwind will ensure that every detail matches Figma and works flawlessly.

### How I plan on tackling this issue
- I will carefully inspect Figma for precise spacing, layout, and components behavior
- Build UI using CSS and Tailwind CSS as appropriate.
- Test across all screen sizes for responsive behavior
- Optimize images, animations, and code for performance

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
My background in web development and responsive design enables me to create visually appealing and functional mobile experiences that align with the project's branding.

### How I plan on tackling this issue
To optimize the simple landing page for mobile responsiveness, I would begin by reviewing the existing layout and identifying elements that may not display well on various mobile screen sizes. I would then implement responsive design techniques, such as using flexible grids, relative units (like percentages or viewport units), and media queries, to ensure the layout adapts seamlessly to different devices.

Next, I would ensure that the existing gradient styles and color scheme are consistently applied throughout the mobile layout to maintain brand identity. I would test the page across a range of mobile devices and screen sizes to confirm that it looks great and functions smoothly.

Finally, I would gather user feedback and conduct performance testing to identify any potential issues, making adjustments as necessary to enhance the user experience.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will optimize the landing page for mobile view to ensure it is fully responsive and provides a seamless experience across various mobile screen sizes. This will involve adjusting the layout so that all elements display correctly and function smoothly on smaller devices.

I will maintain the existing gradient styles used on the page to ensure visual consistency, and I will adhere to the current color scheme to uphold brand uniformity. The goal is to enhance user experience while keeping the design aligned with our established branding guidelines.

I will review the design specifications provided in the Figma link to ensure that all aspects are implemented accurately. I will also conduct thorough testing on different mobile devices to confirm that the landing page performs optimally.

I will provide an estimated time of arrival (ETA) for the completion of this task within four days. This timeframe will allow me to ensure a high-quality outcome that meets all requirements.

Thank you for the opportunity, and I look forward to delivering an optimized mobile landing page.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
To optimize the landing page for mobile responsiveness, I will ensure the layout looks great and functions smoothly across various screen sizes by using CSS media queries for adjustments. I will consistently apply the existing gradient styles and adhere to the current color scheme to maintain brand uniformity. After implementing these changes, I will test the page on different devices to ensure a smooth user experience.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 

### How I plan on tackling this issue

How I plan on tackling this issue
-  will carefully inspect Figma for precise spacing, layout, and components behavior
- Build UI using CSS and Tailwind CSS as appropriate.
- Test across all screen sizes for responsive behavior
- Optimize images, animations, and code for performance

please kindly assign :)
