### ISSUE TITLE
Implement The Registration Screen UI

### ISSUE THREAD

**Issue by Calebux** [mubarak23/chainevents-frontend#18]
Follow Design guide and implement The design 
https://www.figma.com/design/Z1IebD0dM4HMDDnlxzhV6R/CHAINEVENTS-DRAFT?node-id=915-7004&node-type=canvas&t=DaCPbGaPuh6x3rV7-0

**Comment by Emmanex01** [comment]
Could I take over this issue?

**Comment by wheval** [comment]
Hello @Calebux, I'm an experienced frontend developer.
I'd like to take this issue.
I would ensure to implement a pixel-perfect replica of the design.
This would be my first contribution. Thanks
ETA is 1 day.

**Comment by MarcusDavidG** [comment]
Can I take this issue?

**Comment by Yunusabdul38** [comment]
Have view the figma file, I'd love to work on this! and make sure it meets the requirements

**Comment by DanielEmmanuel1** [comment]
Is this issue still available?
I'm a new contributor and would love the opportunity to work on this

I am also a Full-Stack developer with sufficient experience in creating neat UI and I'm confident in my ability to deliver on this issue.

**Comment by ShantelPeters** [comment]
Hi can i please be assigned to this issue @Calebux

**Comment by Benjtalkshow** [comment]
Mind if I take this issue?

I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

My ETA is 48hrs. Thanks

**Comment by Michaelkingsdev** [comment]
Can I contribute to this one?

**Comment by pheobeayo** [comment]
Would love to tackle this!
