### ISSUE TITLE
Implement insight screen Design

### ISSUE THREAD

**Issue by Calebux** [mubarak23/chainevents-frontend#19]
Follow Design guide and implement The design
https://www.figma.com/design/Z1IebD0dM4HMDDnlxzhV6R/CHAINEVENTS-DRAFT?node-id=915-7004&node-type=canvas&t=DaCPbGaPuh6x3rV7-0

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue @Calebux

**Comment by myspace20** [comment]
@ShantelPeters  what is the progress of this issue ?

**Comment by ShantelPeters** [comment]
> @ShantelPeters what is the progress of this issue ?

I’m working on it ,will create a PR soon sir .

**Comment by myspace20** [comment]
Okay
