### ISSUE TITLE
Build Create Event Flow 

### ISSUE THREAD

**Issue by Calebux** [mubarak23/chainevents-frontend#2]
Build the Create Event Flow as per the Figma design provided. This flow should guide users smoothly through the process of creating an event, following the design specifications.

**Requirements:**
Implement the design provided in the Figma link
Ensure that the layout is mobile-responsive.
Follow the gradient style and color scheme from the design.
Ensure that all fields, buttons, and interactions function as per the design specifications.
Test the flow for both mobile and desktop views to ensure consistent performance.

Please refer to the Figma design here: https://www.figma.com/design/Z1IebD0dM4HMDDnlxzhV6R/Untitled?node-id=844-4453&node-type=canvas&t=tRf2C0gaILTQeHdU-0

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello i am a frontend developer and cairo developer and i believe i would be able to tackle this issue effectively. I have experience with building web applications and dapps. And i would be gald to take this up.

### How I plan on tackling this issue
I would develop the page perfectly according to the figma design and also make sure that it is responsive in all screens. I will make sure to adopt best practices when builidng to ensure a pixel perfect build

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer. I will love to work on this. Please assign

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am an advanced computer science student with experience in Java, JavaScript, and Unity. Currently, I am part of SunsetLabs, where I work on the frontend development of the game Citizen of Arcanis. My experience in responsive design and user experience equips me to handle this task effectively, ensuring that the Create Event Flow is visually appealing and functional.



### How I plan on tackling this issue
Design Implementation: I will recreate the Create Event Flow using the Figma design as a guide, ensuring that all visual elements match the provided specifications.

Responsive Design: I will implement a responsive design that adjusts according to the screen size, ensuring that the flow is user-friendly on both mobile devices and desktops.

Functionality of Fields and Buttons: I will ensure that all input fields, buttons, and interactive functions work as specified in the design, including input validation and user feedback for any errors.

Testing: I will conduct thorough testing on multiple devices to confirm that the Create Event Flow functions consistently and smoothly, addressing any issues that arise during testing.

**Comment by Samuel1-ona** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

My background and how it can be leveraged
Hello  a blockchain developer. I will love to work on this issue

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
i will Follow the semantic HTML structure,
Use CSS variables for consistency,
Ensure mobile responsiveness,
Test thoroughly.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Build the create event flow following the figma design as a guide and making sure it is mobile responsive
ETA - 4 days

**Comment by stephanniegb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I’m a frontend engineer with  experience in building responsive, interactive UIs. I’ve worked on implementing pixel-perfect designs, and optimizing performance across various projects. My frontend technologies like css and tailwind will ensure that every detail matches Figma and works flawlessly.

### How I plan on tackling this issue
- I will carefully inspect Figma for precise spacing, layout, and components behavior
- Build UI using CSS and Tailwind CSS as appropriate.
- Test across all screen sizes for responsive behavior
- Optimize images, animations, and code for performance

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello I'm a frontend and blockchain developer. I will love to work on this issue

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
My background in frontend development and UI/UX design allows me to effectively translate designs into functional and visually appealing user interfaces.

### How I plan on tackling this issue
To build the Create Event Flow according to the provided Figma design, I would start by thoroughly reviewing the design to understand all the required steps and interactions involved in the event creation process. Next, I would implement the layout in the codebase, ensuring that it is fully mobile-responsive and adheres to the specified gradient style and color scheme.

I would develop and integrate all necessary input fields, buttons, and interactive elements, ensuring they function as outlined in the design specifications. Throughout the process, I would prioritize user experience to create a seamless and intuitive flow.

Finally, I would test the entire flow for consistency and performance across both mobile and desktop views, making adjustments as needed to ensure a smooth user experience.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
To implement the Create Event Flow based on the Figma design, I will start by analyzing the design to outline the user journey and identify the key components needed. I will set up the project for mobile responsiveness using CSS media queries and flexbox/grid layouts.

I will apply the specified gradient style and color scheme consistently across all elements while ensuring accessibility. I will integrate key fields and buttons with immediate validation feedback for users to enhance the interactive experience.

Once the implementation is complete, I will conduct thorough testing on various devices to verify that the flow meets the design specifications and performs seamlessly. This approach will ensure that I deliver a user-friendly and visually appealing Create Event Flow.
