### ISSUE TITLE
Implement the Side modal Screen

### ISSUE THREAD

**Issue by Calebux** [mubarak23/chainevents-frontend#25]
Follow the design guide to build the Side modal screen 

Figma file: https://www.figma.com/design/Z1IebD0dM4HMDDnlxzhV6R/CHAINEVENTS-DRAFT?node-id=1438-2088&node-type=canvas&t=I8gdtc3kZaUKhEPg-0

**Comment by SudiptaPaul-31** [comment]
Can I work on this issue

**Comment by gidson5** [comment]
Could I take a shot at this? I have experience with React and Tailwind ETA 1 day

**Comment by Yunusabdul38** [comment]
Can I be assigned to this?

**Comment by martinvibes** [comment]
hey @Calebux can i work on this

**Comment by Jemiiah** [comment]
@Calebux pls i would love to work on this issue
