### ISSUE TITLE
Redesign Brand Identity and Components

### ISSUE THREAD

**Issue by Calebux** [mubarak23/chainevents-frontend#5]
Redesign the project's brand identity, including key components in the UI. This will involve updating the color scheme, typography, logo, and other visual elements to ensure a more cohesive, modern look that aligns with the project's mission and values.

**Tasks:**

Logo Redesign:
Create a new logo or update the existing one.
Ensure it works well in different sizes (favicon, social media, website).
Color Scheme Update:
Revise the current color palette to reflect the new brand identity.
Ensure accessibility and readability are considered.

Typography:
Update the fonts used across the project.
Ensure the typography is consistent and readable, both on web and mobile.

Documentation Update:
After redesigning, update the style guide and any related documentation to reflect the changes.

Requirements:
Follow the gradient style and color scheme of the current project, but feel free to suggest improvements.
Ensure the new design is responsive and optimized for mobile and desktop.
Ensure accessibility standards (WCAG) are met.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
I would loveto work on this!

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I will redesign the brand identity by updating the logo, color scheme, and typography to create a modern, cohesive look. The design will be responsive, accessible (WCAG-compliant), and documented in an updated style guide.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
hello I will love to work on this

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
I will create a logo that is responsive to all screens. I will follow the color scheme. I will update the fonts across the projects and make sure to be consistent. And after redesigning, I will update the style guide and any related documentation to reflect the changes. 

Please assign me, I am ready to work.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
My background in UI/UX design and branding enables me to create a cohesive and modern visual identity that resonates with users while adhering to accessibility standards.

### How I plan on tackling this issue
To tackle the redesign of the project's brand identity, I would first conduct a thorough analysis of the current branding elements to identify areas for improvement while ensuring alignment with the project's mission and values. 

1. Logo Redesign: I would create several logo concepts, focusing on versatility for various sizes, including favicons, social media, and website use. 

2. Color Scheme Update: I would revise the existing color palette, incorporating modern colors while ensuring accessibility and readability, following WCAG guidelines.

3. Typography: I would select new fonts that enhance readability and maintain consistency across web and mobile platforms, ensuring they align with the overall brand identity.

4. Documentation Update:Once the redesign is complete, I would update the style guide and any related documentation to reflect the new branding elements, providing clear guidelines for future use.

5. Responsive Design:Throughout the process, I would ensure that all new design elements are responsive and optimized for both mobile and desktop views.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To tackle the logo redesign and overall branding update, I’ll start by assessing the current logo and identifying key elements that resonate with our brand identity. I want to create a logo that is versatile, ensuring it looks great at any size, from a favicon to social media icons and website headers.

Next, I’ll revise the color palette, keeping in mind our existing gradient style while exploring improvements that enhance accessibility and readability. I’ll ensure the colors not only align with our new identity but also meet WCAG standards for contrast.

For typography, I’ll select fonts that reflect our brand’s personality while ensuring consistency across all platforms. I’ll focus on readability for both web and mobile devices, aiming for a cohesive look throughout.

Finally, once the designs are complete, I’ll update the style guide and any related documentation to capture these changes. This will ensure that our branding remains uniform and easily accessible for future projects. Throughout the process, I’ll prioritize responsiveness and accessibility to create an inclusive experience for all users.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi I'm Alvaro Lazarus a blockchain developer, and a new member of Dojo Coding. I really like digital marketing and have worked on a few hackathons were my main job was designing the brand and frontend of our project which makes me confident I can make a really well done redesign of ChainEventts.

### How I plan on tackling this issue
I will start by checking the current look and overall feel of the brand to understand who are the main users and what are the most important points. From there I'll redesign the logo and color palette to match the feel of the brand and give it a professional yet iconic look, and chose a fitting font to wrap everything nicely together. Finally I'll update the Documentation to reflect the changes made.

Best regards,
Lazarus

**Comment by ooochoche** [comment]
@Calebux  I would love to work on this

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
@Calebux I've gone through the description and would love to work on this issue

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm agnik, i have experience in product design.


### How I plan on tackling this issue
I would love to:

Design modern gradient-based logo with versatile scaling
Update color system with accessible palette
Apply consistent typography hierarchy
Create living style guide

ETA:
4-5 days max

**Comment by mimisavage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, I’m Mimi Sav, a frontend and blockchain developer. This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.



### How I plan on tackling this issue
To start, I will focus on the logo redesign, ensuring it reflects our brand essence and works well across various platforms, including favicons and social media. I will explore both new concepts and updates to the existing logo for versatility.

Next, I will revamp the color scheme, aiming for a palette that enhances visual appeal while ensuring accessibility and readability. This will involve selecting colors that resonate with our brand narrative and comply with WCAG standards.

For typography, I will identify fonts that offer clarity and consistency across all platforms, emphasizing legibility on both web and mobile. I will then update our style guide and related documentation to incorporate these new elements.

Throughout the process, I will maintain alignment with the existing gradient style while exploring potential improvements. I will ensure the final design is responsive and optimized for diverse devices.


ETA: 48hrs

**Comment by FolushoJoseph** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged

I’m a brand and product designer with experience helping startups create cohesive visual identities from ideation to launch. 

I’ve worked on redesigning logos, updating color schemes, and refining typography for consistency and accessibility across web and mobile platforms. I also develop style guides to maintain brand standards.

Here is a link to my portfolio to get a preview of my expertise:
Be.net/folushojoseph

### How I plan on tackling this issue
I would start by reviewing the current brand identity, analyzing what works well and what areas need improvement. For the logo, I’d focus on creating a versatile design that maintains clarity at different sizes. 

In updating the color scheme, I’d ensure it aligns with the brand's values while improving accessibility. For typography, I’d choose fonts that enhance readability and consistency across platforms.

Throughout the process, I’d maintain a user-first approach, ensuring the design is responsive and optimized for both web and mobile. Finally, I’d update the style guide to reflect all changes and ensure smooth implementation.
