### ISSUE TITLE
Build and optimise Participants screen

### ISSUE THREAD

**Issue by Calebux** [mubarak23/chainevents-frontend#7]
Develop the Participants screen to improve user interaction and functionality. This screen should list participants with options for searching, filtering, and sorting to enhance usability. The design must be responsive for both desktop and mobile, adhering to the existing color scheme, typography, and component styles for brand consistency.

**Requirements:**
Implement a responsive layout for seamless mobile and desktop experiences.
Integrate search, filter, and sorting options for easier navigation.
Ensure alignment with existing UI components and styling guidelines.

**Expected Outcome:**
A fully functional, optimized Participants screen that enhances usability and matches the project’s brand identity across all devices.

Figma Link: https://www.figma.com/design/Z1IebD0dM4HMDDnlxzhV6R/CHAINEVENTS-DRAFT?node-id=939-86&node-type=canvas&t=J6gwNSrttiqJv22U-0

**Comment by Joy-Adah** [comment]
Hi. My name is Joy. Can I take up this issue?

**Comment by mubarak23** [comment]
@Joy-Adah can you provide a progress on this issue

**Comment by Joy-Adah** [comment]
Hey @mubarak23 I'll have a draft pr ready today
